### ISSUE TITLE
Multiple ports?

### ISSUE THREAD

**Issue by nahrens007** [Shadow1356/chat-experiment#19]
I am curious as to why the server is using multiple ports? 1060 for listening and 1065 for sending? Why not just use a single port to simplify things? Does the socket API your using not allow it?

**Comment by Shadow1356** [comment]
I did it to try it out. I'm manually implementing asynchronous socket IO handling server side, and I could do the same thing client side (then I could only use 1 port). Instead, client side I'm spawning a different thread for each port. 1 thread for sending, 1 for receiving (if I didn't do this somehow, then I could get a deadlock). This is mainly so I can see how this stuff works and the performance benefits/detriments from one approach to the next (if this wasn't for educational value, and I actually wanted to deploy this system, then I would probably use asyncio or another asynchronous API both client and server side).

**Comment by nahrens007** [comment]
Okay that makes sense. On my repo (https://github.com/redninja2/ChatProgram) I'm also using two threads on the client (for send/receive) but I'm only using one port. I don't think that using a single port for send/receive would actually cause a deadlock, would it? It would just be using a single thread for both might?

**Comment by Shadow1356** [comment]
I looked into it, and I think you are correct. It can only deadlock if it's used on the same thread. Dedicating 1 thread to reading and 1 thread to writing should not create an issue. After I'm finished implementing what I am currently doing, I'll fix this. Thanks.
